### PR TITLE
Fix PluginSuppression tests in PHP 7.4

### LINKED ISSUE #4477: Gracefully handle plugins that cause validation errors
In either Transitional mode or Reader mode, when a given plugin causes a validation error, the user will be presented with the option to prevent the plugin from running on AMP pages:

- A new section in the AMP plugin admin screen enabling users to specify which of the installed plugins can be deactivated during amp responses when in transitional or reader mode (plugin suppression)
- Alternatively, the UI to deactivate plugins in AMP responses could be integrated into the plugin list table.
- In Reader Mode, the AMP plugin will automatically remove invalid markup and will notify the user there is an issue with the plugin, and the administrator of the site highlighting the offending markup and plugin (same to be done for Transitional mode and Standard mode).
- Provide assistance when encountering validation errors

### PR DESCRIPTION
**Pull request by westonruter**
## Summary

Also simple comparison for version change since use of `version_compare()` is unnecessary for inequality check.

Fixes #4477.

## Checklist

- [x] My pull request is addressing an open issue (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by westonruter** [comment]
Welp, that didn't work.

```
1) AmpProject\AmpWP\Tests\Unit\PluginSuppressionTest::test_render_suppressed_plugins

Trying to access array offset on value of type bool

/tmp/wordpress/src/wp-content/plugins/amp/src/PluginSuppression.php:410
/tmp/wordpress/src/wp-content/plugins/amp/tests/php/src/Unit/PluginSuppressionTest.php:421
```

File: src/PluginSuppression.php [hunk 1]
```diff
@@ -407,7 +407,7 @@ public function render_suppressed_plugins() {
 										?>
 									<?php endif; ?>
 
-									<?php if ( version_compare( $suppressed_plugins[ $plugin_slug ][ Option::SUPPRESSED_PLUGINS_LAST_VERSION ], $plugin['Version'], '!=' ) ) : ?>
+									<?php if ( $suppressed_plugins[ $plugin_slug ][ Option::SUPPRESSED_PLUGINS_LAST_VERSION ] !== $plugin['Version'] ) : ?>
```
Comment (pierlon) [inline src/PluginSuppression.php:410]: The issue is that `$suppressed_plugins[ $plugin_slug ]` returns `false`; in PHP < 7.4 accessing a non-existent key would return `null`, but on PHP 7.4 this now throws an error.

Comment (westonruter) [reply src/PluginSuppression.php:410]: I had some more logic errors in the tests. I believe this is fixed now with dd9b9b35d.

**Review by pierlon — APPROVED** [review]
