### PR TITLE
Issue #1157: Display schema.org image data for 'attachment' post type

### LINKED ISSUE #1157: There is missing schema.org data on attachment pages
As reported in this [support topic](https://wordpress.org/support/topic/structured-data-error-for-attachment-pages-media/) by [@shrewdies](https://wordpress.org/support/users/shrewdies/), the schema.org data doesn't have an `image` value on attachment pages. 

Steps to reproduce:
1. Select an image in `wp-admin/` > Media > Library
2. In the [Attachment Details](https://native-ampconfdemo.pantheonsite.io/wp-admin/upload.php?item=312) modal, click 'View attachment page'
view-attachment-page

3. Enter the [URL of that page](https://native-ampconfdemo.pantheonsite.io/312/) into the [Google Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fnative-ampconfdemo.pantheonsite.io%2F312%2F)

Expected: There is 'image' data
Actual: That value is missing

image-value-missing

### PR DESCRIPTION
**Pull request by kienstra**
On 'attachment' pages in Native AMP, there's no schema.org data for the image. 

This adds a conditional to check for the post type of 'attachment.' 

It's possible that the attachment is a video, like a `.mov` file. In that case, it won't return an image.

As reported in this support topic: https://wordpress.org/support/topic/structured-data-error-for-attachment-pages-media/

Closes #1157.

### CODE REVIEW

File: includes/amp-helper-functions.php [hunk 1]
```diff
@@ -524,6 +524,8 @@ function amp_get_post_image_metadata( $post = null ) {
 
 	if ( has_post_thumbnail( $post->ID ) ) {
 		$post_image_id = get_post_thumbnail_id( $post->ID );
+	} elseif ( 'attachment' === $post->post_type ) {
```
Comment (westonruter) [inline includes/amp-helper-functions.php]: What if the attachment isn't an image? I think this should also include `wp_attachment_is( 'image', $post )`

Comment (kienstra) [reply includes/amp-helper-functions.php]: Thanks, commit [15ea3d](https://github.com/Automattic/amp-wp/pull/1176/commits/15ea3d94c8336c1d614384c6d817ea3dec8a17a4) ensures the attachment is an image.
