### PR TITLE
Fix parsing of HTML5 empty media elements including source and track

### LINKED ISSUE #62: amp-video/amp-audio supports limited children
amp-video only supports `<source>` `<div fallback>` and `<div placeholder>` as children.

amp-audio only supports  `<source>` and `<div fallback>`.

We should reformat the child nodes to match this.

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #62.

### CODE REVIEW

File: includes/utils/class-amp-dom-utils.php [hunk 1]
```diff
@@ -75,6 +75,13 @@ public static function get_dom( $document ) {
 			$document
 		);
 
+		// Force all self-closing tags to have closing tags since DOMDocument isn't fully aware.
+		$document = preg_replace(
+			'#<(' . join( self::$self_closing_tags, '|' ) . ')[^>]*>(?!</\1>)#',
```
Comment (ThierryA) [inline includes/utils/class-amp-dom-utils.php]: No changes require: while both work, usually the glue string is the first parameter when using `join()` which is an alias of `implode()`.
