### PR TITLE
Use current timestamp if post does not have a date

### LINKED ISSUE #5449: Previews: date is incorrect
## Bug Description

In pre-publish previews, the post date does not appear to be correct. It is set to "51 years ago".

## Steps to reproduce

1. Go to Posts > Add New
2. Write a bit of content, and click on the AMP icon to preview your post.
3. In the window that opens, the post date is incorrect.

## Screenshots

image

### PR DESCRIPTION
**Pull request by pierlon**
## Summary

Uses the current Unix timestamp for the post date if the post does not have one (i.e. post does not have the `post_date_gmt` property set or has the value `0000-00-00 00:00:00`).

Fixes #5449

## Checklist

- [x] My pull request is addressing an open issue (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

File: includes/templates/class-amp-post-template.php [hunk 1]
```diff
@@ -302,15 +302,19 @@ private function build_post_data() {
 	 * @return int Post publish UTC timestamp.
 	 */
 	private function build_post_publish_timestamp() {
-		$format    = 'U';
-		$timestamp = (int) get_post_time( $format, true, $this->post, true );
+		if ( empty( $this->post->post_date_gmt ) || '0000-00-00 00:00:00' === $this->post->post_date_gmt ) {
```
Comment (pierlon) [inline includes/templates/class-amp-post-template.php:307]: @westonruter Do you think a check should be added to only use `time()` when the post status is either `draft`, `pending` or `auto-draft`?

Comment (westonruter) [reply includes/templates/class-amp-post-template.php:307]: I don't think that is necessary, as that special value would only ever happen for a non-published post anyway. 

Apparently this post statuses that include that special value are called `date_floating`, which means “whether the post has a floating creation date.” If it has no creation date, then `now()` should be assumed no?

https://github.com/WordPress/wordpress-develop/blob/19513ff6a0fc27b2ff7e9debeb6e94b7e1b4d658/src/wp-includes/post.php#L3775-L3810

File: includes/templates/class-amp-post-template.php [hunk 2]
```diff
@@ -302,15 +302,19 @@ private function build_post_data() {
...
+			$timestamp = time();
+		} else {
+			$format    = 'U';
+			$timestamp = (int) get_post_time( $format, true, $this->post, true );
 
-		/** This filter is documented in wp-includes/general-template.php. */
-		$filtered_timestamp = apply_filters( 'get_the_date', $timestamp, $format, $this->post );
```
Comment (westonruter) [inline includes/templates/class-amp-post-template.php:309]: Should the `$timestamp` not still get filtered when it is `time()`?

File: includes/templates/class-amp-post-template.php (hunk 1 above)
Comment (pierlon) [reply includes/templates/class-amp-post-template.php:307]: Oh interesting. So yes, if no creation date, use `time()` (assuming that you mistakenly used `now()` for `time()`).

File: includes/templates/class-amp-post-template.php (hunk 2 above)
Comment (pierlon) [reply includes/templates/class-amp-post-template.php:309]: Addressed in https://github.com/ampproject/amp-wp/pull/5450/commits/db113382378c66b523c099ae182a2a12ab5b5bb4.

File: includes/templates/class-amp-post-template.php (hunk 1 above)
Comment (westonruter) [reply includes/templates/class-amp-post-template.php:307]: Yes, I meant `time()`.

**Review by westonruter — APPROVED** [review]
Before | After
-------|------
image | image
