### PR TITLE
Fix Backtrack Limit Exhausted

### LINKED ISSUE #993: 500 Error when PREG Backtrack Limit Exhausted
PHP versions 5.2.x have a default value of `100000` on `pcre.backtrack_limit`.  We stumbled on the issue in `0.7-beta` with the work supporting amp-bind.

We are using `amp-iframe` as a container for a table with a lot of rows and some javascript to help filter that table.  We're injecting the iframe source through the `srcdoc` attribute.  The regex matching tag attributes eventually will hit backtrack limit, fail with a `PREG_BACKTRACK_LIMIT_ERROR` silently, and `AMP_Dom_Utils::convert_amp_bind_attributes` will return `null`.

Further along the stack, this `null` value will be fed to `DOMDocument` which will cause a fatal error.
I'm opening up a PR shortly with some failing tests.  I've made an attempt at modifying the regex, but I can't get all the tests to pass with my changes so I'm opening up this issue to the broader community.

### PR DESCRIPTION
**Pull request by christianc1**
## Work In Progress for #993 

Adding some tests to make the issue apparent.

Fixes #993.

### CODE REVIEW

File: tests/test-class-amp-dom-utils.php [hunk 1]
```diff
@@ -145,4 +145,58 @@ public function test_html5_empty_elements() {
...
+	 *
+	 * @return array An array of arrays holding an integer representation of iterations.
+	 */
+	public function get_table_row_iterations() {
+		return array(
+			array( 1 ),
+			array( 10 ),
+			array( 100 ),
+			array( 1000 ),
+			array( 10000 ),
```
Comment (westonruter) [inline tests/test-class-amp-dom-utils.php]: Per https://github.com/Automattic/amp-wp/issues/993#issuecomment-372139130 I think this 10,000 value should just be removed. I don't think it is reasonable to expect a `srcdoc` to be this large, let alone an AMP document as a whole.

File: tests/test-class-amp-dom-utils.php [hunk 2]
```diff
@@ -145,4 +145,58 @@ public function test_html5_empty_elements() {
...
+		}
+
+		$html .= '</table></body></html>';
+
+		$to_convert = '<amp-iframe
+		sandbox="allow-scripts"
+		srcdoc="' . htmlentities( $html ) . '">
+		</amp-iframe>';
+
+		$converted = AMP_DOM_Utils::convert_amp_bind_attributes( $to_convert );
```
Comment (westonruter) [inline tests/test-class-amp-dom-utils.php]: The `$converted` variable isn't being used, so should it even be set?

File: tests/test-class-amp-dom-utils.php [hunk 3]
```diff
@@ -145,4 +145,58 @@ public function test_html5_empty_elements() {
...
+				</tr>
+			';
+		}
+
+		$html .= '</table></body></html>';
+
+		$to_convert = '<amp-iframe
+		sandbox="allow-scripts"
+		srcdoc="' . htmlentities( $html ) . '">
+		</amp-iframe>';
```
Comment (westonruter) [inline tests/test-class-amp-dom-utils.php]: I think it is better to use `sprintf()` here:

```php
$to_convert = sprintf( 
    '<amp-iframe sandbox="allow-scripts" sandbox="allow-scripts" srcdoc="%s"></amp-iframe>',
    htmlentities( $html )
);
```

File: tests/test-class-amp-dom-utils.php (hunk 2 above)
Comment (christianc1) [reply tests/test-class-amp-dom-utils.php]: If the regex engine fails *for any reason*, `$converted` will be `null` here.  I was originally testing for `null` in this test case, `$this->assertNotNull( $converted );`. I then later opted to fail with a specific `PREG_BACKTRACK_LIMIT_ERROR` to give more insight into why the test actually failed.  I'll remove this.

File: tests/test-class-amp-dom-utils.php (hunk 3 above)
Comment (christianc1) [reply tests/test-class-amp-dom-utils.php]: 👍

File: includes/utils/class-amp-dom-utils.php [hunk 4]
```diff
@@ -64,8 +64,21 @@ public static function get_dom( $document ) {
...
+		 * are known not to contain amp-bind style attributes, it's more performant to skip the
+		 * conversion.  Use of this filter is only recommended if documents are very large and
+		 * at risk of exceeding regex engine limits.
+		 *
+		 * @param bool   $convert  True if bind attributes should be converted, false otherwise. Default true.
+		 * @param string $document Valid HTML document possibly containing bind attributes to be converted.
+		 */
+		if ( apply_filters( 'amp_convert_bind_attributes', true, $document ) ) {
+			// @todo In the future consider an AMP_DOMDocument subclass that does this automatically. See <https://github.com/Automattic/amp-wp/pull/895/files#r163825513>.
+			$document = self::convert_amp_bind_attributes( $document );
```
Comment (westonruter) [inline includes/utils/class-amp-dom-utils.php]: Note that while the conversion is conditional here, the restoration is not conditional. Below you can see `restore_amp_bind_attributes` gets called even though no conversion may have been done. This isn't necessarily a problem, but it is a wasted search/replace operation.

File: includes/utils/class-amp-dom-utils.php [hunk 5]
```diff
@@ -231,14 +244,15 @@ public static function convert_amp_bind_attributes( $html ) {
...
+		$converted = preg_replace_callback(
 			// Match all start tags that probably contain a binding attribute.
-			'#<(?P<name>[a-zA-Z0-9_\-]+)(?P<attrs>\s+[^>]+\]=[^>]+)\s*>#',
+			'#<(?P<name>[a-zA-Z0-9_\-]+)(?P<attrs>\s[^>]+\]=[^>]+)>#',
 			$replace_callback,
 			$html
 		);
 
-		return $html;
+		// If the conversion failed, pass the original HTML as DOMDocument may still be able to use it.
```
Comment (westonruter) [inline includes/utils/class-amp-dom-utils.php]: Maybe good to explain why it failed. Linking back the GitHub issue and mentioning backtracking would be good.

File: includes/utils/class-amp-dom-utils.php [hunk 6]
```diff
@@ -64,8 +64,21 @@ public static function get_dom( $document ) {
...
-		// @todo In the future consider an AMP_DOMDocument subclass that does this automatically. See <https://github.com/Automattic/amp-wp/pull/895/files#r163825513>.
-		$document = self::convert_amp_bind_attributes( $document );
+		/**
+		 * Convert Bind Attributes.
+		 *
+		 * Use this filter to skip converting amp-bind style attributes. On large documents that
+		 * are known not to contain amp-bind style attributes, it's more performant to skip the
+		 * conversion.  Use of this filter is only recommended if documents are very large and
+		 * at risk of exceeding regex engine limits.
+		 *
```
Comment (westonruter) [inline includes/utils/class-amp-dom-utils.php]: Add `@since 0.7`

File: includes/utils/class-amp-dom-utils.php [hunk 7]
```diff
@@ -64,8 +64,21 @@ public static function get_dom( $document ) {
...
+		 * @param bool   $convert  True if bind attributes should be converted, false otherwise. Default true.
+		 * @param string $document Valid HTML document possibly containing bind attributes to be converted.
+		 */
+		if ( apply_filters( 'amp_convert_bind_attributes', true, $document ) ) {
```
Comment (westonruter) [inline includes/utils/class-amp-dom-utils.php]: So you see this being necessary? Is it required in your use case? How big are the HTML documents you're working with?

File: tests/test-class-amp-dom-utils.php [hunk 8]
```diff
@@ -145,4 +145,57 @@ public function test_html5_empty_elements() {
...
+		$to_convert = sprintf(
+			'<amp-iframe sandbox="allow-scripts" srcdoc="%s"> </amp-iframe>',
+			htmlentities( $html )
+		);
+
+		AMP_DOM_Utils::convert_amp_bind_attributes( $to_convert );
+
+		if ( preg_last_error() === PREG_BACKTRACK_LIMIT_ERROR ) {
+			$this->fail( 'Failed when backtrack limit was exhausted.' );
+		}
```
Comment (westonruter) [inline tests/test-class-amp-dom-utils.php]: When there is no error this test will run without any assertions. That will mean this test will appear as a warning when PHPUnit is called with ` --strict`.

I think it would be better to do:

```php
$this->assertSame( PREG_NO_ERROR, preg_last_error(), 'Probably failed when backtrack limit was exhausted.' );
```

File: includes/utils/class-amp-dom-utils.php (hunk 7 above)
Comment (christianc1) [reply includes/utils/class-amp-dom-utils.php]: The HTML document which led to this error was the only one I've identified, so my sample size is small lol.

In my particular case, without this filter, the document will be passed through the conversion method and `DOMDocument` will be able to load it.  This filter is not strictly necessary, I just thought it was a convenient way for a developer to bypass an operation that they know will not serve a purpose.  That said, I don't want to pollute the codebase with obscure filters that might be misused.  I'll leave it up to you to decide whether it should be included.  I'm happy to remove it.

Comment (christianc1) [reply includes/utils/class-amp-dom-utils.php]: I re-thought this, this filter only confuses the issue.  I'll remove, I don't see a strong enough use case to include it.
