### PR TITLE
Fix handling responses to form submissions from an AMP Cache

### LINKED ISSUE #1356: Error messages in AMP pages when using a Form
Hello,

The Form at the bottom of our web pages briefly displays a “Form sent successfully” message and then redirects users to a “Thanks” page. The form uses ContactForm7.

Unfortunately, the AMP version of these same pages doesn’t do either one thing or the other: no succesful message and no redirection.
We noticed we don't get in the AMP pages the usual message on mandatory fields that are left empty by the user.

And we found 2 error messages in our code (when we check the page in Developer mode in Chrome). See below.

The problem is that users don’t have any verification that their form was sent to us so they insist clicking on the Submission button several times, creating fustration on them and filling up our email foder with dozens of copies of the same forms.

Original URL (CF7 works great here): https://dragutierrez.com/tratamientos/medicina-estetica/dermapen/
AMP URL (where CF7 doesn't work): https://dragutierrez-com.cdn.ampproject.org/c/s/dragutierrez.com/tratamientos/medicina-estetica/dermapen/?amp

These are the error messages we get:
- - - - - - - - - - - - - - - - - - - - - - - - 
Powered by AMP zap HTML – Version 1534444305877 https://dragutierrez-com.cdn.ampproject.org/c/s/dragutierrez.com/tratamientos/cirugia-plastica/ginecomastia/precio-de-la-ginecomastia/?amp
dragutierrez-com.cdn.ampproject.org/:1 Failed to load https://dragutierrez.com/wp-admin/admin-ajax.php?action=ampcf7_submit_form&_wp_amp_action_xhr_converted=1&__amp_source_origin=https%3A%2F%2Fdragutierrez.com: The 'Access-Control-Allow-Origin' header contains the invalid value '*.ampproject.org'. Origin 'https://dragutierrez-com.cdn.ampproject.org' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
log.js:187 Form submission failed: Error: XHR Failed fetching (https://dragutierrez.com/...): Failed to fetch ... log.js:187
- - - - - - - - - - - - - - - - - - - - - - - - 

That js.187 line says:
fn.apply(this.win.console, messages);

I'm not sure but I wonder if there could be an issue with the way your plugin deals with Ajax.
Any help appreciated.

NOTE: we've also tested a simpler scenario using WP default theme (twenty seventeen and deactivating CF7 Redirection plugin.

Thanks in advance,

Jose Delgado

### PR DESCRIPTION
**Pull request by westonruter**
It turns out that submitting a form from a page on an AMP cache is currently failing with the plugin. An error 

> Failed to load https://example.com/contact/?_wp_amp_action_xhr_converted=1&__amp_source_origin=https%3A%2F%2Fexample.com#contact-form-6: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://example-com.cdn.ampproject.org' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> Form submission failed: Error: XHR Failed fetching (https://example.com/...): Failed to fetch​​​

The reason is that the plugin was not sending back the proper CORS response headers as detailed in the [CORS in AMP](https://www.ampproject.org/docs/fundamentals/amp-cors-requests) docs. In particular, the `Access-Control-Allow-Origin` header was not being sent, and the `Origin` checking was not taking into the AMP Cache domains.

In this PR:

* Refactor code for handling HTTP requests and responses by extracting code from `AMP_Theme_Support` and the entirety of `AMP_Response_Headers` to form a new class `AMP_HTTP`.
* Add the AMP cache origins to the `allowed_redirect_hosts` so that `wp_validate_redirect()` will allow such origins.
* Send CORS response headers and handle AMP XHR requests even in Classic mode.
* Add `Access-Control-Allow-Credentials:true` and `Vary:origin` response headers.
* Prevent overriding any previously-sent `Access-Control-Expose-Headers` response headers.

To test this, you need to have the code deployed publicly and then access your site on the AMP cache, specifically a page that has a contact form on it. For an easy way to determine the AMP Cache URL for any given URL, see https://ampbyexample.com/advanced/using_the_google_amp_cache/#amp-cache-url-format

Fixes #1356.

### CODE REVIEW

**Comment by westonruter** [comment]
For reviewing, you'll want to look at the commit after the first (i.e. 1870954), since the first commit is just the code re-org.

File: tests/test-class-amp-theme-support.php [hunk 1]
```diff
@@ -62,16 +62,13 @@ public function test_init() {
 		$_REQUEST['__amp_source_origin'] = 'foo';
 		$_GET['__amp_source_origin']     = 'foo';
 		AMP_Theme_Support::init();
-		$this->assertNotEquals( 10, has_action( 'widgets_init', array( self::TESTED_CLASS, 'register_widgets' ) ) );
-
-		// Ensure that purge_amp_query_vars() didn't execute.
-		$this->assertTrue( isset( $_REQUEST['__amp_source_origin'] ) ); // WPCS: CSRF ok.
+		$this->assertFalse( has_action( 'widgets_init', array( self::TESTED_CLASS, 'register_widgets' ) ) );
+		$this->assertFalse( has_action( 'widgets_init', array( self::TESTED_CLASS, 'register_widgets' ) ) );
```
Comment (amedina) [inline tests/test-class-amp-theme-support.php]: Eliminate duplicate
